export const metadata = {
    title: "PW E-Commerce",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="es">
            <body style={{
                margin: 0,
                padding: 0,
                boxSizing: 'border-box',
                backgroundColor: '#0a0a0a',
                fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif'
            }}>
                {children}
            </body>
        </html>
    );
}